### ISSUE TITLE
Back button in destination and activity page

### ISSUE THREAD

**Issue by sreenadh** [Kites-Foundation/hello-munnar-frontend#171]
## Describe the bug
Back button in destination and activity page not working properly when those pages are accessed directly.

## Steps to reproduce
Open below urls directly and click back button. It seems it is using history.back();
https://hellomunnar.in/activity/ACT001
https://hellomunnar.in/destination/D-035

## Expected behavior
Should go to their parent page

**Comment by daliyajohn** [comment]
issue related to #167

**Comment by gautamkrishnar** [comment]
Hi @daliyajohn this is not related to #167 reopening this one. Please check  #176 for the fix.
