### ISSUE TITLE
Add enough margin/padding to the last item in the carousels

### ISSUE THREAD

**Issue by gautamkrishnar** [Kites-Foundation/hello-munnar-frontend#177]
## Describe the bug
Last item in the following carousel and all other carousels should have a right margin/padding as required:
<img width="281" alt="Screenshot 2021-02-23 at 12 34 45 AM" src="https://user-images.githubusercontent.com/8397274/108757279-a2ea0f00-756f-11eb-8388-ef43e10ecb68.png">

It should be same as the following first item's left margin/padding:
<img width="223" alt="Screenshot 2021-02-23 at 12 40 42 AM" src="https://user-images.githubusercontent.com/8397274/108757702-31f72700-7570-11eb-9bbf-fd8d40c13b31.png">

**Comment by avronr** [comment]
I saw this too.

**Comment by gautamkrishnar** [comment]
Fixed on #208
