### ISSUE TITLE
Fix CSP for google analytics

### ISSUE THREAD

**Issue by gautamkrishnar** [Kites-Foundation/hello-munnar-frontend#185]
Google analytics requires the CSP policies mentioned in https://www.bounteous.com/insights/2017/07/20/using-google-analytics-and-google-tag-manager-content-security-policy/ to work properly. 

Due wrong CSP policies mentioned in our [netlify.toml](https://github.com/Kites-Foundation/hello-munnar-frontend/blob/develop/netlify.toml) the google analytics might not work properly. It may report some wrong metrics. CSP needs to be updated to correct params for GA.

**Comment by tomahawk-pilot** [comment]
@gautamkrishnar i am not seeing any errors related to CSP

**Comment by gautamkrishnar** [comment]
We can ignore this for now then. We can fix this on the fly via sentry as they pops up,

**Comment by gautamkrishnar** [comment]
@tomahawk-pilot Just found this as well https://content-security-policy.com/faq/ looks like we are good to go.
