### ISSUE TITLE
App consuming 1GB of storage space as cache when used for 5 minutes

### ISSUE THREAD

**Issue by gautamkrishnar** [Kites-Foundation/hello-munnar-frontend#224]
App's caching mechanism is broken. It is using too much of data even while used on the browser even for a short interval of time.

![Screenshot 2021-03-19 at 11 49 22 PM](https://user-images.githubusercontent.com/8397274/111825688-c2c1e800-890d-11eb-99da-a09a8840499e.png)

**Comment by tomahawk-pilot** [comment]
even i noticed that.

**Comment by tomahawk-pilot** [comment]
we need to do something about that. 
i think its recaching every time.

**Comment by sreenadh** [comment]
@tomahawk-pilot @gautamkrishnar The reason is the random display of images on home page. The images are cached locally. So exclude images from cache (except logo and ui elements) and show placeholder image when the page is in offline mode.

**Comment by naseemshah** [comment]
So I researched about this. Looks like this only happens in the browsers were React Developer Tools Extension is installed.

I tried in My  Google Chrome where the React Dev tools were installed. As expected, it used anywhere from 500mb to 1gb usage in the first few minutes. 

Then i tried the same thing in Google Chrome in Incognito mode and in Microsoft Edge, where the memory usage was less to none.

![image](https://user-images.githubusercontent.com/44234669/133412317-fc766f3e-4fa3-444f-a79c-9da7283d25f8.png)

Seems like Dev tools is caching the images over and over which leads to high usage of memory.

**Comment by naseemshah** [comment]
Sorry guys, It's no the issue of dev tools, after refreshing It uses high memory again. As @sreenadh  mentioned, at every refresh new random images are cached. Thus using high memory usage.

**Comment by nikhilnathr** [comment]
As the most of the storage is used by the images from activities, destinations and screenshots I added an exception to those routes using the regex `^((?!(/activities/|/destinations/|/screenshots/)).)*$` for the 3 caches in the service worker and the memory consumption remained under 50MB.
Shall I open a PR with this change, or is there a better approach to reduce the cache size?

![image](https://user-images.githubusercontent.com/35567322/133486927-391f95b8-210f-4222-b508-c6697a654162.png)

**Comment by sreenadh** [comment]
@nikhilnathr Please open the PR. Also add a placeholder image to be displayed when the app is used offline.

**Comment by gautamkrishnar** [comment]
@nikhilnathr please hold on, I have to dig into this issue a little bit.

**Comment by gautamkrishnar** [comment]
@nikhilnathr The issue was not with any images getting cached two times. It was mostly due to lots of buggy repeated code written in the service worker which didn't even match the function's actual prototype.  I guess it is just copy-pasted from somewhere even without checking its functionality.

I removed all of those functions. Now the memory size is just 170MB (It may vary depending on the images loaded).  
![Screenshot 2021-09-16 at 10 42 54 PM](https://user-images.githubusercontent.com/8397274/133656788-58f8d75a-74ba-4558-a6d4-f2a7177487fd.png)

We still have the following action items: 
- Compress the images in the app (This can be ignored since we will be moving to CMS soon.
- Improve the offline support of the app by adding proper service worker and fallback codes.
