### ISSUE TITLE
[Asset Management]Migrate images/svgs from SPA to Amazon S3

### ISSUE THREAD

**Issue by riginoommen** [Kites-Foundation/hello-munnar-frontend#36]
## Describe the bug
Move the SPA assets such as SVG, PNG etc files to amazon s3 and provide the urls. to the assets.

**Comment by riginoommen** [comment]
- [ ] Configure amazon s3 and move assets. from spa.
https://github.com/Kites-Foundation/hello-munnar-frontend/tree/develop/src/assets/images

**Comment by rejahrehim** [comment]
@tomahawk-pilot  Could you please address this issue ASAP. Need all assets in one place like S3 and use it throughout the APP

**Comment by tomahawk-pilot** [comment]
Resolved
Https://cdn.hellomunnar.in
Origin shield + cloudfront + cloudflare proxy
Access to upload given to @lespaceman
